# Repository Configuration - Build
# Format of this file is documented at https://github.com/7Ji/arch_repo_builder#config
dephash_strategy: strict
basepkgs: [base-devel, bc, distcc, ccache, rust, rust-bindgen]
home_binds: [.cache/ccache, .config/ccache]
pkgbuilds:
  # m1n1 bootloader for Asahi (Apple Silicon)
  m1n1:
    url: GH/1usOS/PKGBUILDs
    branch: asahi
    subtree: /
  # u-boot for Asahi (Apple Silicon)
  uboot-asahi:
    url: GH/1usOS/PKGBUILDs
    branch: asahi
    subtree: /
  # Mesa for Asahi (Apple Silicon)
  mesa-asahi:
    url: GH/1usOS/PKGBUILDs
    branch: asahi
    subtree: /
  # makedeps: [spirv-llvm-translator, python-packaging, python-yaml]
  # Linux Kernel for Asahi (Apple Silicon)
  linux-asahi:
    url: GH/1usOS/PKGBUILDs
    branch: asahi
    subtree: /
  # misc configs for Asahi (Apple Silicon)
  asahi-configs:
    url: GH/1usOS/PKGBUILDs
    branch: asahi
    subtree: /
  # maintenance scripts for Asahi (Apple Silicon)
  asahi-scripts:
    url: GH/1usOS/PKGBUILDs
    branch: asahi
    subtree: /
  # firmware extractor for Asahi (Apple Silicon)
  asahi-fwextract:
    url: GH/1usOS/PKGBUILDs
    branch: asahi
    subtree: /
