name: Upload repository to GitHub Release (x86_64)

# Controls when the workflow will run
on:
  # Runs on pushes targeting the default branch
  #push:
  #  branches: ["main"]
  # Run the workflow every Night at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Download latest repository archives
        run: |
          # GitHub API URL to the GitHub Release
          release_url="https://api.github.com/repos/1usOS/PKGBUILDs/releases/tags/archive"
          # List of all assets download URL
          assets_url_list="$(curl -s "$release_url" | sed -n 's/.*"browser_download_url": "\(.*\)".*/\1/p')"
          # Filter for target architecture
          assets_url_list="$(echo "$assets_url_list" | grep .x86_64.xz)"

          # Download repositories - 1usOS
          curl -LO "$(echo "$assets_url_list" | grep 1usOS_ | tail -n 1)"
          # Download repositories - misc
          curl -LO "$(echo "$assets_url_list" | grep misc_ | tail -n 1)"

      - name: Extract repository archives
        run: |
          output_folder="output"
          mkdir -p "$output_folder"
          for archive in *.xz; do
              if [[ -f $archive ]]; then
                  echo "Extracting $archive to $output_folder"
                  tar -xJf "$archive" --strip-components=1 -C "$output_folder"
              fi
          done

      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "output/*"
            tag: "x86_64"
            makeLatest: false
            allowUpdates: true
            removeArtifacts: true
            omitBody: true